### ISSUE TITLE
Ability to rename tabs and books.

### ISSUE THREAD

**Issue by kylak** [tonny-kohar/alkitab-suite#1]
To have the ability to rename tabs and books would be helpful.

Thanks a lot for any help !

**Comment by tonny-kohar** [comment]
I will put this feature on todo list

**Comment by kylak** [comment]
Thanks a lot for that and for all the work you did, the software you developed is very very good!

**Comment by tonny-kohar** [comment]
Just implemented rename tab in the latest source code, It will be available on next release

**Comment by kylak** [comment]
Thanks a lot for that !
