### ISSUE TITLE
MVC pattern.

### ISSUE THREAD

**Issue by kylak** [tonny-kohar/alkitab-suite#2]
Hello, 

I cloned the repo and opened the project on Netbeans but the code didn't look to be under the MVC pattern.

Could it be possible to structure the code according to the MVC pattern ?
It could help to develop the software.

Thanks for your answer.

**Comment by tonny-kohar** [comment]
It is under MVC pattern. Please see https://blogs.oracle.com/geertjan/spotting-the-mvc-pattern-in-the-netbeans-platform

Note: Alkitab Bible Study is build on top of Netbeans Platform and JSword Library.

**Comment by tonny-kohar** [comment]
And please see https://www.appservgrid.com/refcards/refcards/dzonerefcards/rc080-010d-netbeans-platform_2.pdf

It helps to undertand netbeans platform where alkitab is build on top.

**Comment by kylak** [comment]
Ok thanks I will look at the links you have given.

**Comment by tonny-kohar** [comment]
To make it easier to understand in term of MVC
- in terms of MVC, Netbeans Platform is the the Controller, Alkitab is the the View, JSwod is the Model.
- Alkitab provide View for the Model (bible text, verse, list of books, etc) by querying using JSword API
- Netbeans Platform act as Controller and Container for the View, by providing lifecycle management, registration handle (menu, action, plugins, etc) for View, 

But it is recommended to not think as MVC, but as modular application framework instead.
- The use of lookup is extensively used.
- Each namespace is a module (eg: bookshelf namespace, bookviewer namespace, etc)
- Whenever possible each view is provided as JPanel/JComponent (basic standard java swing) and finally wrapped in TopComponent (Netbeans specific things)

Note the concept of Lookup is very important for modular application framework and heavily used. Lookup is provided by netbeans (netbeans specific things), It is modeled after Event Bus design pattern and observer/subscriber/consumer pattern.
- https://dzone.com/articles/design-patterns-event-bus
- https://hackernoon.com/event-bus-implementation-s-d2854a9fafd5
- http://wiki.netbeans.org/DevFaqLookup
- https://dzone.com/articles/netbeans-lookups-explained

**Comment by kylak** [comment]
Thanks a lot.
