### ISSUE TITLE
Fonts too small; Options window does not appear.

### ISSUE THREAD

**Issue by descendingnerdliness** [tonny-kohar/alkitab-suite#3]
openjdk 11.0.6 2020-01-14
I have a large, high-resolution screen and the program appears to be sized for a very small one. The Tools.Options window does not appear when invoked, so I found the alkitab.conf file and changed -J-Dsun.java2d.dpiaware to 'true', which made no noticeable difference.
The program looks really nice and I have wanted to try to use it for some time now, but each version I have tried has this problem, whether on Kubuntu 16.04, or now on 18.04.
While it is unusable, I was able to test other windows: the 'View Options', 'Plugins', and 'Book Installer' windows do appear.
I appreciate your attention.
Patrick

**Comment by tonny-kohar** [comment]
I will look at it regarding the openjdk dan Kubuntu font size problem.
In the mean time if you are able to open the options windows through any means, you can change the font size for the text. See the screenshot

![image](https://user-images.githubusercontent.com/13114803/78576140-7a253200-7856-11ea-9a00-28351652f442.png)

And the program (itself) font size , you can change it through the alkitab.conf file by appending "--fontsize XX" (note: double dash) eg:
default_options="<other-options> --fontsize 18"

**Comment by tonny-kohar** [comment]
I just released Alkitab BIble Study 4.0-beta1 (note: it is beta version) that address those bug
- Options Windows can't be opened
- Better DPI aware for High Resolution Screen

It is available at https://www.kiyut.com/products/alkitab/alkitab-4_0-beta1.zip

Let me know, if this version fix the bug on your end, thx

**Comment by tonny-kohar** [comment]
Fixed on v4.0
