### ISSUE TITLE
How to add other books/sermons to it?

### ISSUE THREAD

**Issue by passionate2023** [tonny-kohar/alkitab-suite#6]
Hi,

How to add other books/sermons to it?

Thanks

**Comment by tonny-kohar** [comment]
Basically you download the available books from crosswire and add it to Alkitab Bible Study.
Please follow the following tutorial
[https://www.kiyut.com/products/alkitab/faq.php#faq-book-install](url)

**Comment by passionate2023** [comment]
I have some own sermon books
I have some own language dictionary
How to create it or add it to alkitab and add to it? finally rebuilt it...
What are the formats i need to create the content

Please help me....

also does it support unicode characters?

**Comment by tonny-kohar** [comment]
The modules (books, dictionary, commentaries) are written and formatted in OSIS format. OSIS is an XML Schema definition for Bibles and other Biblical research texts. It support unicode.

Please see the following regarding OSIS format

- [https://wiki.crosswire.org/OSIS_Bibles](https://wiki.crosswire.org/OSIS_Bibles) 
- [https://wiki.crosswire.org/Main_Page](https://wiki.crosswire.org/Main_Page) Module development section

**Comment by ariasrodolfo** [comment]
the format is THE SWORD 
here is a short guide:
http://crosswire.org/sword/develop/swordmodule/
